---
roles:
  - name: geerlingguy.docker
    version: "6.0.3"

collections:
  - name: community.general
    version: "5.6.0"
  - name: hetzner.hcloud
    version: "1.8.2"
  - name: community.docker
    version: "3.1.0"
