---
roles:
  - name: geerlingguy.docker
    version: "7.0.1"

collections:
  - name: community.general
    version: "7.5.5"
  - name: hetzner.hcloud
    version: "2.1.1"
  - name: community.docker
    version: "3.4.8"
