---
roles:
  - name: geerlingguy.docker
    version: "7.1.0"

collections:
  - name: community.general
    version: "7.5.5"
  - name: hetzner.hcloud
    version: "3.0.0"
  - name: community.docker
    version: "3.4.8"
