---
roles:
  - name: geerlingguy.docker
    version: "6.2.0"

collections:
  - name: community.general
    version: "7.2.1"
  - name: hetzner.hcloud
    version: "2.1.1"
  - name: community.docker
    version: "3.4.8"
