---
roles:
  - name: geerlingguy.docker
    version: "4.1.3"

collections:
  - name: community.general
    version: "4.5.0"
  - name: hetzner.hcloud
    version: "1.6.0"
  - name: community.docker
    version: "2.1.1"
