---
roles:
  - name: geerlingguy.docker
    version: "5.2.1"

collections:
  - name: community.general
    version: "5.6.0"
  - name: hetzner.hcloud
    version: "1.9.0"
  - name: community.docker
    version: "3.1.0"
