---
roles:
  - name: geerlingguy.docker
    version: "7.4.1"

collections:
  - name: community.general
    version: "8.4.0"
  - name: hetzner.hcloud
    version: "3.0.0"
  - name: community.docker
    version: "3.8.1"
