---
roles:
  - name: geerlingguy.docker
    version: "6.0.3"

collections:
  - name: community.general
    version: "5.8.1"
  - name: hetzner.hcloud
    version: "1.9.0"
  - name: community.docker
    version: "3.2.1"
