---
roles:
  - name: geerlingguy.docker
    version: "7.0.1"

collections:
  - name: community.general
    version: "7.4.0"
  - name: hetzner.hcloud
    version: "2.1.1"
  - name: community.docker
    version: "3.8.1"
