---
roles:
  - name: geerlingguy.docker
    version: "7.1.0"

collections:
  - name: community.general
    version: "8.4.0"
  - name: hetzner.hcloud
    version: "4.2.1"
  - name: community.docker
    version: "3.8.1"
