---
roles:
  - name: geerlingguy.docker
    version: "7.1.0"

collections:
  - name: community.general
    version: "8.6.6"
  - name: hetzner.hcloud
    version: "3.0.0"
  - name: community.docker
    version: "3.8.1"
