---
roles:
  - name: geerlingguy.docker
    version: "6.2.0"

collections:
  - name: community.general
    version: "7.0.0"
  - name: hetzner.hcloud
    version: "1.11.0"
  - name: community.docker
    version: "3.4.5"
