---
roles:
  - name: geerlingguy.docker
    version: "6.0.4"

collections:
  - name: community.general
    version: "6.2.0"
  - name: hetzner.hcloud
    version: "1.9.0"
  - name: community.docker
    version: "3.2.1"
