---
roles:
  - name: geerlingguy.docker
    version: "5.1.0"

collections:
  - name: community.general
    version: "5.5.0"
  - name: hetzner.hcloud
    version: "1.8.2"
  - name: community.docker
    version: "3.0.2"
