---
roles:
  - name: geerlingguy.docker
    version: "4.0.0"

collections:
  - name: community.general
    version: "3.5.0"
  - name: hetzner.hcloud
    version: "1.6.0"
  - name: community.docker
    version: "1.9.0"
