---
roles:
  - name: geerlingguy.docker
    version: "4.2.1"

collections:
  - name: community.general
    version: "4.7.0"
  - name: hetzner.hcloud
    version: "1.6.0"
  - name: community.docker
    version: "2.3.0"
