---
roles:
  - name: geerlingguy.docker
    version: "6.1.0"

collections:
  - name: community.general
    version: "7.2.1"
  - name: hetzner.hcloud
    version: "1.11.0"
  - name: community.docker
    version: "3.4.5"
