---
roles:
  - name: geerlingguy.docker
    version: "6.1.0"

collections:
  - name: community.general
    version: "6.5.0"
  - name: hetzner.hcloud
    version: "1.10.0"
  - name: community.docker
    version: "3.4.2"
