---
roles:
  - name: geerlingguy.docker
    version: "5.2.1"

collections:
  - name: community.general
    version: "5.8.1"
  - name: hetzner.hcloud
    version: "1.8.2"
  - name: community.docker
    version: "3.1.0"
