---
- name: Install ufw
  apt:
    name: ufw
    state: present
    update_cache: true

- name: Enable ufw service
  community.general.ufw:
    state: enabled

- name: Deny all incoming traffic
  community.general.ufw:
    default: deny
    direction: incoming
  notify: reload ufw

- name: Allow all outgoing traffic
  community.general.ufw:
    default: allow
    direction: outgoing
  notify: reload ufw

- name: Allow ssh access
  community.general.ufw:
    rule: allow
    port: "4567"
    proto: tcp
  notify: reload ufw

- name: Allow minecraft server access
  community.general.ufw:
    rule: allow
    port: "{{ minecraft_server_port }}"
  notify: reload ufw

- name: Flush handlers
  meta: flush_handlers
