name: Lint Provisioning Scripts

on: [ push, pull_request ]

jobs:
  lint-terraform:
    env:
      TERRAFORM_VERSION: "0.14.3"
    runs-on: ubuntu-20.04
    steps:
      - name: Install terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Initialize Terraform
        run: terraform init

      - name: Validate terraform files
        run: terraform validate

      - name: Ensure Terraform files follow the official style guides
        run: terraform fmt -check -recursive

  lint-ansible-playbooks:
    env:
      ANSIBLE_VERSION: "2.10.0"
      PYTHON_VERSION: "3.9.1"
      ANSIBLE_LINT_VERSION: "4.3.7"
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Ansible & Ansible lint & dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible-lint==${{ env.ANSIBLE_LINT_VERSION }} ansible==${{ env.ANSIBLE_VERSION }}

      - name: Install external collections
        run: ansible-galaxy collection install -r requirements.yml

      - name: Install external roles
        run: ansible-galaxy role install -r requirements.yml

      - name: Lint Ansible Playbooks
        run: |
          ansible-playbook minecraft-server-configuration.yml --syntax-check
          ansible-lint minecraft-sever-configuration.yml --exclude=${HOME}/.ansible/roles/
